### ISSUE TITLE
标签很多的时候，中间cell会不显示，而且会出现很多空白的地方

### ISSUE THREAD

**Issue by QETHAN** [lqcjdx/YLTagsChooser#1]

**Comment by ApesTalk** [comment]
@QETHAN 感谢你的反馈，最近抽时间看了下，问题已修复，欢迎测试和指正。

**Comment by Shawkaine** [comment]
请教一下，你这是滑动的时候出现空白的吗？跟长度不一定有关系吗？我是相同size的cell在滑动时屏幕边缘那一列就会出现空白
