### ISSUE TITLE
Can we retain selected tag ?

### ISSUE THREAD

**Issue by ruchiteasternts17Dec** [lqcjdx/YLTagsChooser#2]
Hey can we retain selected tag once i select 4 tags out of 20 tag then again i select tag is it possible that there 4 tags were shows selected ?

**Comment by ApesTalk** [comment]
Yes you can. I have updated the code.
Maybe you have multiple pages in your APP will use the tags selector, and each time you select the tags, the type is not the same, it is recommended to package the tag as an object: YLTag, each time you display YLTagsChooser, you can pass the last selected The value to it.
