### ISSUE TITLE
设置 collectionView.contentInset 时候，就会有问题

### ISSUE THREAD

**Issue by nihaolifei999** [lqcjdx/YLTagsChooser#3]
建议添加对于  collectionView.contentInset 的考虑
还有 设置了    self.footerReferenceSize = CGSizeMake(self.collectionView.bounds.size.width, 10);
footer并没有显示？

**Comment by ApesTalk** [comment]
@nihaolifei999 最新代码已支持设置contentInset和footerReferenceSize。
