### ISSUE TITLE
flowlayout 里的 bug

### ISSUE THREAD

**Issue by nihaolifei999** [lqcjdx/YLTagsChooser#4]
calculateFrames 中 
if(_framesArray.count > 0){
        return;
}
是否应改为[ _framesArray removeAllObjects];
否则 当cell 个数 减少时 会崩溃

或者用其他方式修复这个bug

**Comment by ApesTalk** [comment]
@nihaolifei999 如你所说，这里是可以改成[ _framesArray removeAllObjects];来解决你这种数据源个数发生改变后奔溃的问题。这里我直接return是因为这里考虑到在列表滚动的时候也会调用calculateFrames方法，直接retrun可避免重复计算。当时只考虑了数据源不变的情况。感谢你的反馈，这里的代码逻辑确实有待优化。

**Comment by nihaolifei999** [comment]
part1 
  [ _framesArray removeAllObjects];我只考虑了奔溃问题 没有考虑到效率，这样虽然可以解决因cell个数变化而崩溃（或 cell中data变化width也能随之改变）的问题，但随之而来的是页面卡顿很严重，望能优化。
part2 
  还有就是不知道是我collection代理写的有问题还是layout里面的问题，当cell个数为0时候, 我设置的sectionHeaderView/sectionFooterView 也不显示 了。
