### ISSUE TITLE
继Bug#4

### ISSUE THREAD

**Issue by nihaolifei999** [lqcjdx/YLTagsChooser#5]
part1
[ _framesArray removeAllObjects];我只考虑了奔溃问题 没有考虑到效率，这样虽然可以解决因cell个数变化而崩溃（或 cell中data变化width也能随之改变）的问题，但随之而来的是页面卡顿很严重，望能优化。
part2
还有就是不知道是我collection代理写的有问题还是layout里面的问题，当cell个数为0时候, 我设置的sectionHeaderView/sectionFooterView 也不显示了。

**Comment by ApesTalk** [comment]
@nihaolifei999 感谢反馈！
part2已修复，见最新代码。
part1的话，目前还没优化。我建议在每次数据源发生改变，reoadData之前调用一下calculateFrames这个方法去计算一下高度，之后不需要再重复计算了。目前的一个思路是重写UICollectionVIew的reloadData方法，你有什么好的建议吗？

**Comment by ApesTalk** [comment]
暂不考虑使用重写UICollectionView的几个刷新方法来解决这个问题。 
如果你的数据源是会改变的，你应该在数据源发生改变后，先调用reCalculateFrames刷新frames再调用reloadData。
