### ISSUE TITLE
如果初始的orignalTags数组中没有元素,请求后刷新并没有调用返回cell

### ISSUE THREAD

**Issue by XavierLost** [lqcjdx/YLTagsChooser#7]
如果初始的orignalTags数组中没有元素,为空的话,网络加载热词之后, (如果你的数据源是会改变的，你应该在数据源发生改变后，先调用该方法刷新frames再调用reloadData。- (void)reCalculateFrames) 使用以上方法,并没有去调用返回cell的方法,所以导致计算不了位置,不知道怎么解决

**Comment by ApesTalk** [comment]
@lotus-lotus 抱歉，我之前的那句话有点问题，我这里提供一个思路，你可以像这样做：
//动态加载热词之后赋值
_orignalTags = newTags;
//数据源发生了改变，必须要reload，否则会导致数组越界
 [collectionView reloadData];
//拿到layout，通知其重新计算一下frames
 YLWaterFlowLayout *layout = (YLWaterFlowLayout *)collectionView.collectionViewLayout;
 [layout reCalculateFrames];
//最好再刷新一下
 [collectionView reloadData];

**Comment by XavierLost** [comment]
哦,我就是这样的,不过网络延迟的话,会有占位文字,只能这么解决了,感谢
